export const classrooms = [
    {
        id: 1,
        title: "Science Lab",
        image: "https://images.freeimages.com/images/large-previews/9b2/chem-lab-1-1479990.jpg?fmt=webp&h=350",
        description: "A state-of-the-art science lab equipped for innovative experiments.",
        location: "Building A, Room 101",
        date: "2025-02-01",
    },
    {
        id: 2,
        title: "Computer Lab",
        image: "https://t4.ftcdn.net/jpg/02/20/24/05/360_F_220240507_Z8WDjgJliVAL5i41G2WjQtAVkSC066lV.jpg",
        description: "Modern computer lab with high-speed internet and latest software.",
        location: "Building B, Room 202",
        date: "2025-02-02",
    },
    {
        id: 3,
        title: "Library",
        image: "https://ripsgroupjjn.org/ripsjjn/library.jpg",
        description: "A well-stocked library with thousands of books for students.",
        location: "Building C, Room 303",
        date: "2025-02-03",
    },
    {
        id: 4,
        title: "Art Room",
        image: "https://www.collierschools.com/cms/lib/FL01903251/Centricity/Domain/1773/DSC_0011.JPG",
        description: "A creative space filled with painting, sculpting, and design materials.",
        location: "Building D, Room 104",
        date: "2025-02-04",
    },
    {
        id: 5,
        title: "Music Room",
        image: "https://www.stollerykids.com/images/inside-alberta-childrens-hospital/music-therapy.jpg",
        description: "Equipped with instruments and sound systems for musical education.",
        location: "Building E, Room 205",
        date: "2025-02-05",
    },
    {
        id: 6,
        title: "Mathematics Lab",
        image: "https://www.bodleianshop.co.uk/cdn/shop/articles/Maths_books.jpg?v=1649931225",
        description: "An interactive space with tools for hands-on math learning and problem-solving.",
        location: "Building F, Room 306",
        date: "2025-02-06",
    },
    {
        id: 7,
        title: "Physics Lab",
        image: "https://engineering.purdue.edu/ECN//Fileman/06d7b963982c78b4d203bc84cbb67a34.jpg",
        description: "A fully equipped lab for physics experiments and research.",
        location: "Building G, Room 407",
        date: "2025-02-07",
    },
    {
        id: 8,
        title: "Lecture Hall",
        image: "https://www.vanderbilt.edu/jetlaw/wp-content/uploads/sites/356/2019/04/Large-Classroom.jpeg",
        description: "A large auditorium for guest lectures and interactive learning sessions.",
        location: "Building H, Room 508",
        date: "2025-02-08",
    },
];
  
export const festivals = [
    {
        id: 1, 
        title: "Spring Fest",
        image: "https://feeds.abplive.com/onecms/images/uploaded-images/2025/01/23/9bb83de58b0b57e8e79b1724b7f40d321737646825401958_original.jpg",
        description: "A colorful celebration of spring with music, dance, and food.",
        location: "Main Courtyard",
        date: "2025-03-15",
    },
    {
        id: 2, 
        title: "Cultural Day",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoMe1fs-yMMOXsz75Xa4BqsvD_9_9PYZeNwtrVxM8jg9moQoeKB4ff4ur7NbDkd9qlFP0&usqp=CAU",
        description: "A showcase of diverse cultures with traditional performances.",
        location: "Auditorium",
        date: "2025-04-10",
    },
    {
        id: 3, 
        title: "Sports Meet",
        image: "https://newhorizongurukul.in/wp-content/uploads/2024/02/sports_day12.jpg",
        description: "An annual event featuring exciting sports competitions.",
        location: "Sports Field",
        date: "2025-05-20",
    },
    {
        id: 4, 
        title: "Science Fair",
        image: "https://www.nsta.org/sites/default/files/2022-06/STEM_Showcase.jpg",
        description: "Students showcase innovative science projects and experiments.",
        location: "Exhibition Hall",
        date: "2025-06-05",
    },
    {
        id: 5, 
        title: "Music Festival",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnreH08sRBgRm3dt7PJdJDM93PsIkQs1lThQ&s",
        description: "Live music performances by students and guest artists.",
        location: "Open-Air Stage",
        date: "2025-07-12",
    },
    {
        id: 6, 
        title: "Art Exhibition",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgp-QWL9s1HzFdBpL02wnABZP5j7NiN3fssw&s",
        description: "An exhibition displaying stunning artwork by talented students.",
        location: "Art Gallery",
        date: "2025-08-18",
    },
    {
        id: 7, 
        title: "Drama Night",
        image: "https://activetheatremovement.wordpress.com/wp-content/uploads/2024/06/whatsapp-image-2024-06-22-at-23.14.43_5e73f3e9.jpg",
        description: "A theatrical evening featuring plays and dramatic performances.",
        location: "Black Box Theatre",
        date: "2025-09-25",
    },
    {
        id: 8, 
        title: "Food Carnival",
        image: "https://sandipwaghmare.com/projects/pilcrow-website/wp-content/themes/pilcrow/img/food-art-demo.jpg",
        description: "A delicious fest with food stalls offering cuisines from around the world.",
        location: "School Grounds",
        date: "2025-10-10",
    },
];

  
export const events = [
    {
        id: 1, 
        title: "Science Exhibition",
        image: "https://zioninternationalpublicschool.in/wp-content/uploads/2024/02/Display-of-Science-Models-by-our-young-genius-.jpeg",
        description: "Students display their innovative projects and experiments.",
        location: "Gymnasium",
        date: "2025-06-05",
    },
    {
        id: 2, 
        title: "Annual Day",
        image: "https://5.imimg.com/data5/SELLER/Default/2022/12/GV/IG/EM/163516196/stage-decoration-for-school-annual-day.jpeg",
        description: "A grand celebration with performances, awards, and speeches.",
        location: "Stadium",
        date: "2025-07-10",
    },
    {
        id: 3, 
        title: "Workshop on AI",
        image: "https://th-i.thgim.com/public/incoming/nwkc5p/article68067973.ece/alternates/FREE_1200/16April_Campus_Rojavanam.jpg",
        description: "An insightful workshop on Artificial Intelligence and its applications.",
        location: "Coimbatore",
        date: "2025-08-25",
    },
    {
        id: 4, 
        title: "Debate Competition",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Debate_at_the_University_of_Tartu.JPG",
        description: "Students engage in a battle of wits on current affairs and global issues.",
        location: "Lecture Hall 2",
        date: "2025-09-15",
    },
    {
        id: 5, 
        title: "Career Guidance Seminar",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Children_at_an_education_fair_in_Kerala%2C_India.jpg",
        description: "Experts provide career insights and guidance to students.",
        location: "Conference Room",
        date: "2025-10-05",
    },
    {
        id: 6, 
        title: "Inter-School Quiz",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/94/Syedna_Mufaddal_Saifuddin_Barkaat_al_Quran_Competition.jpg",
        description: "A thrilling quiz contest with participation from various schools.",
        location: "Auditorium",
        date: "2025-11-20",
    },
    {
        id: 7, 
        title: "Art & Craft Workshop",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Kids_working_on_an_art_project.jpg",
        description: "A hands-on session for students to explore their creativity.",
        location: "Art Room",
        date: "2025-12-10",
    },
    {
        id: 8, 
        title: "Coding Hackathon",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Hackathon_at_Glasgow_University_2013_%2810595568956%29.jpg",
        description: "A competitive event where students collaborate to solve coding challenges.",
        location: "Computer Lab",
        date: "2026-01-15",
    },
];

 